spring:
  rabbitmq:
    host: ${RABBIT_HOST:rabbitmq}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
application:
  fuseki:
    realm: fdk
    port: 8080
    context-path: fuseki
    store-path: store
    dataset-names:
      - ds
    enable-verbose-logging: true

---
spring:
  config.activate.on-profile: develop
